# The full repository name
repo: sujirodev/forgejo-sdk

# Service type (forgejo or github)
service: forgejo

# Base URL for Forgejo instance if using forgejo service type (optional)
# Default: https://forgejo.org
base-url: https://codeberg.org

# Changelog groups and which labeled PRs to add to each group
groups:
  -
    name: BREAKING
    labels:
      - kind/breaking
  -
    name: SECURITY
    labels:
      - kind/security
  -
    name: GENERAL
    default: true
  -
    name: FEATURES
    labels:
      - kind/feature
  -
    name: FIXES
    labels:
      - kind/bug

# regex indicating which labels to skip for the changelog
skip-labels: skip-changelog|backport\/.+|has/backport
