name: Renovate

on:
  workflow_dispatch:
  # Run Renovate every night at 01:23.
  schedule:
    - cron: "23 01/4 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.62.0@sha256:83b3d7edf2d7a44eab3cd64dee2cf722c5160fec7f9e2ddde69edebefabafab4
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Renovate
        run: renovate
        env:
          # Forgejo/Gitea specific settings
          RENOVATE_PLATFORM: "forgejo"
          RENOVATE_ENDPOINT: "${{ vars.FORGEJO_API_URL || 'https://codeberg.org/api/v1/' }}"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: "mvdkleijn/forgejo-sdk"
          
          # GitHub token is still needed for fetching changelogs/metadata from github.com
          GITHUB_COM_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          
          # Logging and Author
          LOG_LEVEL: "info"
          RENOVATE_GIT_AUTHOR: "Forgejo SDK Renovate Bot <renovate@noreply.codeberg.org>"