name: Renovate

on:
  workflow_dispatch:
  # Run Renovate every night at 01:23 (24h time, randomly chosen).
  schedule:
    - cron: "23 01 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:43
    steps:
      - uses: actions/checkout@v4
      - run: renovate
        env:
          RENOVATE_ENDPOINT: "https://codeberg.org/api/v1/"
          RENOVATE_PLATFORM: "gitea"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: "mvdkleijn/forgejo-sdk"
          GITHUB_COM_TOKEN: ${ { secrets.TOKEN_GITHUB }}
          