// Copyright 2026 The Forgejo Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	routesFile  = "ROUTES.md"
	readmeFile  = "README.md"
	markerStart = "<!-- route-matrix:start -->"
	markerEnd   = "<!-- route-matrix:end -->"
)

// renderRoutes builds ROUTES.md: the summary by leg, then one line per route.
func (m matrix) renderRoutes() []byte {
	var b bytes.Buffer

	b.WriteString("# Supported routes\n\n")
	b.WriteString("Generated by `make route-matrix` from what the integration suite actually\n")
	b.WriteString("did against each Forgejo version. Do not edit by hand.\n\n")

	b.WriteString(m.legsSentence())
	b.WriteString("\n")

	b.WriteString("| Version | ok | n/a (guard) | declared exception | no test | Total |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for i, l := range m.legs {
		t := m.tally(i)
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %d |\n",
			l.Title(), t.ok, t.guarded, t.exception, t.missing+t.failed, len(m.routes))
	}
	b.WriteString("\n")

	b.WriteString("| Route |")
	for _, l := range m.legs {
		fmt.Fprintf(&b, " %s |", l.Title())
	}
	b.WriteString(" Description |\n|---|")
	for range m.legs {
		b.WriteString("---|")
	}
	b.WriteString("---|\n")

	for _, r := range m.routes {
		fmt.Fprintf(&b, "| `%s` |", r.Name)
		for _, c := range m.cells[r.Name] {
			fmt.Fprintf(&b, " %s |", c.Text)
		}
		fmt.Fprintf(&b, " %s |\n", r.Doc)
	}

	b.WriteString("\nCell values: `ok` (the suite called it and the server answered 2xx),\n")
	b.WriteString("`n/a (>= X.Y.Z)` (the SDK's own version guard refuses to call it on that\n")
	b.WriteString("version), or the reason declared in [`route-exceptions.json`](route-exceptions.json).\n")

	return b.Bytes()
}

// legsSentence names the versions behind the columns.
func (m matrix) legsSentence() string {
	parts := make([]string, 0, len(m.legs))
	for _, l := range m.legs {
		parts = append(parts, fmt.Sprintf("%s (%s)", shortVersion(l.ServerVersion), l.Title()))
	}
	return fmt.Sprintf("Run against Forgejo %s.\n", joinAnd(parts))
}

func joinAnd(parts []string) string {
	switch len(parts) {
	case 0:
		return "no version"
	case 1:
		return parts[0]
	default:
		return strings.Join(parts[:len(parts)-1], ", ") + " and " + parts[len(parts)-1]
	}
}

// renderReadmeBlock builds what goes between the markers in README.md.
func (m matrix) renderReadmeBlock() string {
	var b strings.Builder

	b.WriteString(markerStart + "\n")
	b.WriteString("| Forgejo | Routes ok | n/a (guard) | Declared exception | Total |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for i, l := range m.legs {
		t := m.tally(i)
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d |\n",
			l.Version(), t.ok, t.guarded, t.exception, len(m.routes))
	}
	b.WriteString("\nGenerated from the integration suite on every pull request.\n")
	b.WriteString("Per-route detail: [`ROUTES.md`](ROUTES.md).\n")
	b.WriteString("Declared exceptions: [`route-exceptions.json`](route-exceptions.json).\n")
	b.WriteString(markerEnd)

	return b.String()
}

// replaceReadmeBlock swaps the marked block in README.md, leaving the rest of
// the file untouched.
func replaceReadmeBlock(readme []byte, block string) ([]byte, error) {
	s := string(readme)
	i := strings.Index(s, markerStart)
	j := strings.Index(s, markerEnd)
	if i < 0 || j < 0 || j < i {
		return nil, fmt.Errorf("%s has no %s ... %s block", readmeFile, markerStart, markerEnd)
	}
	return []byte(s[:i] + block + s[j+len(markerEnd):]), nil
}

func (m matrix) writeFiles(root string) error {
	if err := os.WriteFile(filepath.Join(root, routesFile), m.renderRoutes(), 0o644); err != nil { //nolint:gosec // a documentation file
		return err
	}

	path := filepath.Join(root, readmeFile)
	readme, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	updated, err := replaceReadmeBlock(readme, m.renderReadmeBlock())
	if err != nil {
		return err
	}
	if bytes.Equal(readme, updated) {
		return nil
	}
	return os.WriteFile(path, updated, 0o644) //nolint:gosec // a documentation file
}

// verifyFiles is the -check mode CI runs: the working tree must already hold
// exactly what the generator would write.
func (m matrix) verifyFiles(root string) error {
	var stale []string

	got, err := os.ReadFile(filepath.Join(root, routesFile))
	if err != nil || !bytes.Equal(got, m.renderRoutes()) {
		stale = append(stale, routesFile)
	}

	readme, err := os.ReadFile(filepath.Join(root, readmeFile))
	if err != nil {
		return err
	}
	updated, err := replaceReadmeBlock(readme, m.renderReadmeBlock())
	if err != nil {
		return err
	}
	if !bytes.Equal(readme, updated) {
		stale = append(stale, readmeFile)
	}

	if len(stale) > 0 {
		return fmt.Errorf("%s out of date; run `make route-matrix` and commit the result", strings.Join(stale, " and "))
	}
	return nil
}
